version: '3.8'

services:
  nextjs:
    build: .
    container_name: pace-web
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    networks:
      custom_network:
        ipv4_address: 172.21.1.100

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: 103.31.39.37
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - '8080:80'
    networks:
      custom_network:
        ipv4_address: 172.21.1.99

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.1.0/24
