version: '3.8'

services:
  nextjs:
    build: .
    container_name: pace-web
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    networks:
      custom_network:
        ipv4_address: 172.21.1.100

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.1.0/24
