name: Github CI

on:
  push:
    tags:
      - v**

jobs:
  run-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Running deployment production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/html/pace-web/
            sudo git pull origin master
            sudo docker-compose down
            sudo docker-compose up -d --build
            sudo docker system prune -af
